# Generated by Django 4.2.1 on 2023-05-11 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0002_ticket_deadline_alter_ticket_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='deadline',
            field=models.DateField(blank=True, null=True, verbose_name='планируемая дата исполнения'),
        ),
    ]
