# Generated by Django 4.2.1 on 2023-05-19 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('helpdesk', '0006_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(max_length=254)),
                ('notification_type', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='helpdesk.ticket', verbose_name='заявка')),
            ],
            options={
                'verbose_name': 'уведомление о заявке',
                'verbose_name_plural': 'уведомления о заявках',
            },
        ),
    ]
